language: go
go:
  - 1.7.3
branches:
  only:
  - master
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
after_success:
  - gox -osarch "darwin/amd64 windows/amd64 linux/amd64 linux/arm" -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
  - ghr --username yuu --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
